version: '3.8'

services:
  app:
    image: golang:1.22
    container_name: fitness-app
    working_dir: /app
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    command: ["sh", "-c", "go run ."]
    depends_on:
      - redis
      - nats
      - elasticsearch

  redis:
    image: redis/redis-stack:latest
    container_name: redis
    ports:
      - "6379:6379"
      - "8001:8001"
    volumes:
      - redis-data:/data
    restart: always

  nats:
    image: nats:latest
    container_name: nats
    ports:
      - "4222:4222"
      - "8222:8222"  # monitoring UI
    volumes:
      - nats-data:/data
    restart: always
    command: ["-js", "-sd", "/data", "--http_port", "8222"]

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.13.4
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - ES_JAVA_OPTS=-Xms1g -Xmx1g
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - esdata:/usr/share/elasticsearch/data
    restart: always

volumes:
  redis-data:
  nats-data:
  esdata:
